#!/usr/bin/env bash
# script that configures a server to run on nginx and listen on port 80
sudo apt-get -y update
sudo apt-get install nginx -y
sudo ufw enable
sudo ufw allow "Nginx HTPP"
sudo service nginx restart