#!/usr/bin/env bash
# carryout specific functions when asked to byy the system
case "$1" in
    start)
        ./manage_my_process &
        echo $$ > /var/run/my_process.pid
        echo "manage_my_process started"
        ;;
    stop)
        pkill -f "manage_my_process"
        rm -rf var/run/my_process.pid
        echo "manage_my_process stopped"
        sleep 2
        ;;
    restart)
        pkill -f "manage_my_process"
        rm -rf var/run/my_process.pid
        ./manage_my_process restarted &
        echo $$ /var/run/my_process.pid
        echo "manage_my_process restarted"
        ;;
    *)
        echo "Usage: manage_my_process {start|stop|restart}"
    esac
exit 0
