#!/usr/bin/env bash
# This script checks and print
for (( c=1; c<=100; c++ ))
do
    # checks if c is a multiple of 3 and 5
    if [ $((c % 3)) -eq 0 -a $((c % 5)) -eq 0 ]
    then
        echo "FizzBuzz"
    # checks if c is a multiple of 3
    elif [ $((c % 3)) -eq 0 ]
    then
        echo "Fizz"
    # checks if c is a multiple of 5
    elif [ $((c % 5)) -eq 0 ]
    then
        echo "Buzz"
    else
        echo "$c"
    fi
done
