#!/usr/bin/env bash
# This script checks and displays the content /etc/passwd
# username
# user id
# Home directory path for the user
while IFS= read -r line
do
    echo "$line" | cut -d ':' -f1,4,7
done < /etc/passwd
