#!/usr/bin/env bash
# This script is displaying "Best School" 10 times using while loop
i=0
while [ $i -le 9 ]
do
    if [ $i -eq 4 ]
    then
        echo "bad luck"
    elif [ $i -eq 8 ]
    then
        echo "good luck"
    fi
    echo "Best School"
    i=$(( i + 1))
done
