#!/usr/bin/env bash
# nginx running as nginx
# nginx listens on all active IPs on port 8080
sudo service nginx stop
chmod 644 /etc/nginx.conf
sed -Ei 's/\s*#?\s*user .*/user nginx;/' /etc/nginx/nginx.conf
sed -Ei 's/(listen (\[::\]:)?80) /\180 /' /etc/nginx/sites-enabled/default
chown nginx:nginx /etc/nginx/ -R
pkill apache2
sudo nginx service nginx start
