#!/usr/bin/env bash
# nginx running as nginx
sudo chmod 644 /etc/nginx.conf
sed -i -E 's/#user www-data/user nginx/' /etc/nginx/nginx.conf
sed -i 's/80/8080/g' /etc/nginx/sites-available/default
sudo pkill apache2
sudo -u nginx service nginx start
