#!/usr/bin/env bash
# nginx running as nginx
# nginx listens on all active IPs on port 8080
# Lines of code should be 7 or less
sed -i -E 's/#user www-data/user nginx/' /etc/nginx/nginx.conf
sed -i 's/80/8080/g' /etc/nginx/sites-available/default
chown nginx:nginx /etc/nginx/ -R
chmod 644 /etc/nginx.conf
pkill apache
sudo nginx service nginx start
